version: 0.2

phases:
  build:
    commands:
      - cd chapter12/todo-plus-frontend
      - npm i && npm run build
      - aws s3 cp --recursive dist/ s3://aws-dva-c02-2024-todo-list-bucket/
      - aws cloudfront create-invalidation --distribution-id E3C5DPW420K6R9 --paths "/*"